### ISSUE TITLE
Cannot get cloud with firmware v1.14.0-beta.8

### ISSUE THREAD

**Issue by matlabbe** [ouster-lidar/ouster_example#170]
Hi,

I get those errors below trying to use an OS0-32 under ros (latest ouster_example version, March 17 2020: https://github.com/ouster-lidar/ouster_example/commit/68ad03c18c99b536a31ad67ccfb2e2d4aeb9b61c):
```yaml
{
  "alerts": {
    "active": [
      {
        "active": true,
        "category": "UDP_TRANSMISSION",
        "cursor": 8,
        "id": "0x01000015",
        "level": "WARNING",
        "msg": "Client not reachable on lidar data port; check udp_ip, udp_port_lidar, and client machine.",
        "msg_verbose": "Failed to send lidar UDP data to destination host 192.168.1.102:37478",
        "realtime": "1591813750800800256"
      },
      {
        "active": true,
        "category": "UDP_TRANSMISSION",
        "cursor": 9,
        "id": "0x01000018",
        "level": "WARNING",
        "msg": "Client not reachable on IMU port; check udp_ip, udp_port_imu, and client machine.",
        "msg_verbose": "Failed to send imu UDP data to destination host 192.168.1.102:52441",
        "realtime": "1591813750815566080"
      },
      {
        "active": false,
        "category": "UDP_TRANSMISSION",
        "cursor": 10,
        "id": "0x01000015",
        "level": "WARNING",
        "msg": "Client not reachable on lidar data port; check udp_ip, udp_port_lidar, and client machine.",
        "msg_verbose": "Cleared by reinitialization.",
        "realtime": "1591813958463102720"
      },
      {
        "active": false,
        "category": "UDP_TRANSMISSION",
        "cursor": 11,
        "id": "0x01000018",
        "level": "WARNING",
        "msg": "Client not reachable on IMU port; check udp_ip, udp_port_imu, and client machine.",
        "msg_verbose": "Cleared by reinitialization.",
        "realtime": "1591813958463416064"
      },
      {
        "active": true,
        "category": "UDP_TRANSMISSION",
        "cursor": 12,
        "id": "0x01000018",
        "level": "WARNING",
        "msg": "Client not reachable on IMU port; check udp_ip, udp_port_imu, and client machine.",
        "msg_verbose": "Failed to send imu UDP data to destination host 192.168.1.102:38502",
        "realtime": "1591813969488677120"
      },
      {
        "active": true,
        "category": "UDP_TRANSMISSION",
        "cursor": 13,
        "id": "0x01000015",
        "level": "WARNING",
        "msg": "Client not reachable on lidar data port; check udp_ip, udp_port_lidar, and client machine.",
        "msg_verbose": "Failed to send lidar UDP data to destination host 192.168.1.102:33321",
        "realtime": "1591813970488146432"
      }
    ],
    "next_cursor": 14
  },
  "config": {
    "auto_start_flag": 1,
    "azimuth_window": [
      0,
      36000
    ],
    "lidar_mode": "1024x10",
    "multipurpose_io_mode": "OFF",
    "nmea_baud_rate": "BAUD_9600",
    "nmea_ignore_valid_char": 0,
    "nmea_in_polarity": "ACTIVE_HIGH",
    "nmea_leap_seconds": 0,
    "sync_pulse_in_polarity": "ACTIVE_HIGH",
    "sync_pulse_out_angle": 360,
    "sync_pulse_out_frequency": 1,
    "sync_pulse_out_polarity": "ACTIVE_HIGH",
    "sync_pulse_out_pulse_width": 10,
    "timestamp_mode": "TIME_FROM_INTERNAL_OSC",
    "udp_ip": "192.168.1.102",
    "udp_port_imu": 38502,
    "udp_port_lidar": 33321
  },
  "info": {
    "base_pn": "830-101845-E",
    "base_sn": "102005001179",
    "build_date": "2020-04-09T19:38:47Z",
    "build_rev": "v1.14.0-beta.8",
    "image_rev": "ousteros-image-prod-aries-v1.14.0-beta.8-20200409221055-staging",
    "prod_line": "OS-0-32-U1",
    "prod_pn": "840-102144-B",
    "prod_sn": "992020000326",
    "proto_rev": "v1.1.1",
    "status": "RUNNING"
  }
}
```

When launching ouster_viz:
```bash
$ rosrun ouster_viz viz os-992020000326.local 192.168.1.102
Configuring sensor: os-992020000326.local UDP Destination:192.168.1.102
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)
```

When launching os1.launch:
```bash
$ roslaunch ouster_ros os1.launch  os1_hostname:=os-992020000326.local os1_udp_dest:=192.168.1.100
... logging to /home/mathieu/.ros/log/6aa1220c-ab47-11ea-8c25-907841228e31/roslaunch-mathieu-XPS-15-7590-31012.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mathieu-XPS-15-7590:41293/

SUMMARY
========

PARAMETERS
 * /os1_cloud_node/tf_prefix: 
 * /os1_node/lidar_mode: 
 * /os1_node/metadata: 
 * /os1_node/os1_hostname: os-992020000326.l...
 * /os1_node/os1_imu_port: 0
 * /os1_node/os1_lidar_port: 0
 * /os1_node/os1_udp_dest: 192.168.1.100
 * /os1_node/replay: False
 * /os1_node/timestamp_mode: 
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    os1_cloud_node (ouster_ros/os1_cloud_node)
    os1_node (ouster_ros/os1_node)

auto-starting new master
process[master]: started with pid [31032]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6aa1220c-ab47-11ea-8c25-907841228e31
process[rosout-1]: started with pid [31043]
started core service [/rosout]
process[os1_node-2]: started with pid [31050]
process[os1_cloud_node-3]: started with pid [31051]
[ INFO] [1591813381.620413131]: Connecting to sensor at os-992020000326.local...
[ INFO] [1591813381.620922447]: Sending data to 192.168.1.100 using lidar_mode: 1024x10
[ INFO] [1591813381.899638436]: Sensor reconfigured successfully, waiting for data...
[ INFO] [1591813381.900230223]: Wrote metadata to os-992020000326.local.json
[ WARN] [1591813381.900622066]: Unknown sensor firmware version; output may not be reliable
[ WARN] [1591813381.900689542]: Beam angles not found in metadata; using design values
[ INFO] [1591813381.900722503]: Sensor sn: 992020000326 firmware rev: v1.14.0-beta.8
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
Unexpected udp packet length: 6464
...
```

Looking at the topics, we receive imu packets, but not lidar packets:
```
$ rostopic hz /os1_node/imu_packets 
subscribed to [/os1_node/imu_packets]
average rate: 100.003
	min: 0.010s max: 0.010s std dev: 0.00018s window: 95
average rate: 99.995
	min: 0.010s max: 0.011s std dev: 0.00017s window: 196
average rate: 99.997
	min: 0.009s max: 0.011s std dev: 0.00017s window: 296
average rate: 99.991
	min: 0.009s max: 0.011s std dev: 0.00017s window: 303
```
```bash
$ rostopic hz /os1_node/lidar_packets 
subscribed to [/os1_node/lidar_packets]
no new messages
no new messages
no new messages
```

Is it a firmware problem?
