### ISSUE TITLE
GPS time discrepency

### ISSUE THREAD

**Issue by MaxandreOgeret** [ouster-lidar/ouster_example#222]
Hello, 
I am using a Ouster OS1 128 beams Rev2 synced with a GPS using NMEA and PPS.

PPS ans nmea are both locked and working fine, but when running the example ouster ros nodes I get an incorrect time delay of `-0.350`

Which is 0.350s in the future, which is not possible and crates problems further down in my processing pipeline. Do you have any idea how to correct this. I have another sensor synced on the same GPS and it reports 0.005s in the past, which makes much more sense.

Thanks !

**Comment by yulan0215** [comment]
> Hello,
> I am using a Ouster OS1 128 beams Rev2 synced with a GPS using NMEA and PPS.
> 
> PPS ans nmea are both locked and working fine, but when running the example ouster ros nodes I get an incorrect time delay of `-0.350`
> 
> Which is 0.350s in the future, which is not possible and crates problems further down in my processing pipeline. Do you have any idea how to correct this. I have another sensor synced on the same GPS and it reports 0.005s in the past, which makes much more sense.
> 
> Thanks !

Hi! I would like to ask you that can you tell me how did you use GPS to synchronize your LiDAR? I had a GPS and I saw that we need to use TCP API to send command to synchronize the device but I do not know the detail, I will appreciate if you can tell me some, thx!

**Comment by MaxandreOgeret** [comment]
Hey ! I used [this](https://forum.ouster.at/d/74-how-to-synchronize-gps-with-ouster-sensor) tutorial to sync the sensor with GPS, Also for this method you need to plug the NMEA UART signal from the GPS signal to the multipurpose IO of the sensor. Also you need to plug the PPS output from your GPS to the PPS input of the sensor.

I hope it helps !

**Comment by MaxandreOgeret** [comment]
It looks like you are on the right way. You have the PPS locked but not the nmea message. You can receive the nmea message so I think the format is wrong. Maybe you can change that in your GPS config. I believe you are sending a GPGSV message but your should send a GPRMC.

**Comment by yulan0215** [comment]
> It looks like you are on the right way. You have the PPS locked but not the nmea message. You can receive data through the multipurpose IO. So I think the format is wrong. Maybe you can change that in your GPS config. I believe you are sending a GPGSV message but you should send a GPRMC.

Thank you for your quick reply, however, I used the GPS to give GPRMC but the problem was that my Ouster LiDAR could not receive this kind of dataset.

**Comment by MaxandreOgeret** [comment]
Hey, GPRMC should be alright, that's what I use : 

```yaml
{
  "timestamp":
    {
      "time": 1612443355.553434,
      "mode": "TIME_FROM_SYNC_PULSE_IN",
      "time_options":
        { "ptp_1588": 3293, "sync_pulse_in": 1612443355, "internal_osc": 3283 },
    },
  "sync_pulse_in":
    {
      "locked": 0,
      "polarity": "ACTIVE_HIGH",
      "diagnostics":
        { "last_period_nsec": 0, "count": 23065, "count_unfiltered": 35411292 },
    },
  "multipurpose_io":
    {
      "mode": "INPUT_NMEA_UART",
      "sync_pulse_out":
        {
          "polarity": "ACTIVE_HIGH",
          "frequency_hz": 1,
          "angle_deg": 360,
          "pulse_width_ms": 10,
        },
      "nmea":
        {
          "locked": 1,
          "polarity": "ACTIVE_LOW",
          "ignore_valid_char": 0,
          "baud_rate": "BAUD_9600",
          "leap_seconds": 37,
          "diagnostics":
            {
              "decoding":
                {
                  "utc_decoded_count": 2808,
                  "date_decoded_count": 2765,
                  "not_valid_count": 42,
                  "last_read_message": "GPRMC,125507.50,A,5823.0922739,N,02643.5445738,E,0.017,123.2,040221,0.0,E,D*37",
                },
              "io_checks":
                {
                  "start_char_count": 3275,
                  "char_count": 240608,
                  "bit_count": 716039,
                  "bit_count_unfiltered": 716038,
                },
            },
        },
    },
}
```

On the picture you showed your GPS is sending a GPGSV message which doesn't contain the right data. Make sure your GPS sends a GPRMC message.
